apiVersion: v1
kind: Service
metadata:
  name: atharva-vllm
  namespace: atharva-ml
spec:
  type: NodePort
  selector:
    # KServe RawDeployment pods are labeled with app=<deployment name> by default
    app: isvc.atharva-vllm-predictor
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30200

