apiVersion: v1
kind: Service
metadata:
  name: atharva-chat-api
  namespace: atharva-app
spec:
  type: NodePort
  selector: { app: atharva-chat-api }
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30300

